baseURL = "https://dejajackson.me/"
languageCode = "en-us"
title = "Deja Jackson"
theme = "hugo-resume"

[params]
address = "Renton, WA"
firstName = "Deja"
lastName = "Jackson"
phone = "1-206-451-3325"
profileImage = "/laf_portrait.jpg"
showEducation = true
showExperience = true
showProjects = true
