baseURL = "https://dejajackson.me/"
languageCode = "en-us"
title = "Deja Jackson"
theme = "hugo-resume"

[markup.goldmark.renderer]
  unsafe = true

[params]
address = "Renton, WA"
email = "deja.jackson@dejajackson.me"
firstName = "Deja"
lastName = "Jackson"
phone = "1-206-451-3325"
profileImage = "/Senior Portrait.jpg"
showBlog = false
showEducation = true
showExperience = true
showProjects = true
showOpenSource = true
showPublications = true

[[params.handles]]
link = "https://www.linkedin.com/in/deja-jackson-63154494/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/jacksodl23"
name = "GitHub"
