baseURL = "https://dejajackson.me/"
languageCode = "en-us"
title = "Deja Jackson"
theme = ["hugo-embed-pdf-shortcode", "hugo-resume"]
enableInlineShortcodes = true

[markup.goldmark.renderer]
  unsafe = true

[params]
address = "Seattle, WA"
email = "deja.jackson@dejajackson.me"
firstName = "Deja"
lastName = "Jackson"
phone = "1-206-451-3325"
profileImage = "Senior Portrait.jpg"
showSocializations = true

sections = ["publications", "creations", "education", "experience", "contributions"]

[[params.handles]]
link = "https://www.linkedin.com/in/deja-jackson-63154494/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/jacksodl23"
name = "GitHub"

[[params.handles]]
link = "https://github.com/BananaFudgkins"
name = "GitHub"
