baseURL = "https://dejajackson.me/"
languageCode = "en-us"
title = "Deja Jackson"
theme = "hugo-resume"

[markup.goldmark.renderer]
  unsafe = true

[params]
address = "Renton, WA"
firstName = "Deja"
lastName = "Jackson"
phone = "1-206-451-3325"
profileImage = "/laf_portrait.jpg"
showBlog = true
showEducation = true
showExperience = true
showProjects = true

[[params.handles]]
link = "https://www.linkedin.com/in/deja-jackson-63154494/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/BananaFudgkins"
name = "GitHub"

[[params.handles]]
link = "https://bitbucket.org/bananafudgkins/"
name = "Bitbucket"
